package DETApp;


/**
* DETApp/DET.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DET.idl
* Wednesday, March 18, 2009 1:29:10 o'clock AM EDT
*/

public interface DET extends DETOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DET
