package DETApp;


/**
* DETApp/DETHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DET.idl
* Wednesday, March 18, 2009 1:29:10 o'clock AM EDT
*/

abstract public class DETHelper
{
  private static String  _id = "IDL:DETApp/DET:1.0";

  public static void insert (org.omg.CORBA.Any a, DETApp.DET that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DETApp.DET extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DETApp.DETHelper.id (), "DET");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DETApp.DET read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DETStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DETApp.DET value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DETApp.DET narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DETApp.DET)
      return (DETApp.DET)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DETApp._DETStub stub = new DETApp._DETStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DETApp.DET unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DETApp.DET)
      return (DETApp.DET)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DETApp._DETStub stub = new DETApp._DETStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
