package DETApp;


/**
* DETApp/DETOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DET.idl
* Wednesday, March 18, 2009 1:29:10 o'clock AM EDT
*/

public interface DETOperations 
{
  void getRequest (String versionName, String commName, int reqID, String argument);
  double SnmpSetBalance ();
  int SnmpSetQuantity ();
  int buyItem (String item, int qty);
  int printReport ();
  int printReportAfterTransaction ();
  void trapBalance ();
  void trapQuantity ();
  void setRequestForBalance (String versionName, String commName, int reqID, String argument);
  void setRequestForQuantity (String versionName, String commName, int reqID, int argument);

  //long sellItem(int String item, in long qty,in double bal);
  int sellItem (int qty, double bal);
  int tradeItems (String item1, int qty1, String item2, int qty2, String etrader);
  void addGenericTrapType (int genType);
  void signalTrapTypeGeneric (String trapType);
  String getTrapNameGeneric ();
  void addSpecificTrapType (int speType);
  void signalTrapTypeSpecific (String trapType);
  String getTrapNameSpecific ();
} // interface DETOperations
