package DETApp;


/**
* DETApp/DETPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DET.idl
* Wednesday, March 18, 2009 1:29:10 o'clock AM EDT
*/

public abstract class DETPOA extends org.omg.PortableServer.Servant
 implements DETApp.DETOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getRequest", new java.lang.Integer (0));
    _methods.put ("SnmpSetBalance", new java.lang.Integer (1));
    _methods.put ("SnmpSetQuantity", new java.lang.Integer (2));
    _methods.put ("buyItem", new java.lang.Integer (3));
    _methods.put ("printReport", new java.lang.Integer (4));
    _methods.put ("printReportAfterTransaction", new java.lang.Integer (5));
    _methods.put ("trapBalance", new java.lang.Integer (6));
    _methods.put ("trapQuantity", new java.lang.Integer (7));
    _methods.put ("setRequestForBalance", new java.lang.Integer (8));
    _methods.put ("setRequestForQuantity", new java.lang.Integer (9));
    _methods.put ("sellItem", new java.lang.Integer (10));
    _methods.put ("tradeItems", new java.lang.Integer (11));
    _methods.put ("addGenericTrapType", new java.lang.Integer (12));
    _methods.put ("signalTrapTypeGeneric", new java.lang.Integer (13));
    _methods.put ("getTrapNameGeneric", new java.lang.Integer (14));
    _methods.put ("addSpecificTrapType", new java.lang.Integer (15));
    _methods.put ("signalTrapTypeSpecific", new java.lang.Integer (16));
    _methods.put ("getTrapNameSpecific", new java.lang.Integer (17));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DETApp/DET/getRequest
       {
         String versionName = in.read_string ();
         String commName = in.read_string ();
         int reqID = in.read_long ();
         String argument = in.read_string ();
         this.getRequest (versionName, commName, reqID, argument);
         out = $rh.createReply();
         break;
       }

       case 1:  // DETApp/DET/SnmpSetBalance
       {
         double $result = (double)0;
         $result = this.SnmpSetBalance ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // DETApp/DET/SnmpSetQuantity
       {
         int $result = (int)0;
         $result = this.SnmpSetQuantity ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // DETApp/DET/buyItem
       {
         String item = in.read_string ();
         int qty = in.read_long ();
         int $result = (int)0;
         $result = this.buyItem (item, qty);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // DETApp/DET/printReport
       {
         int $result = (int)0;
         $result = this.printReport ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // DETApp/DET/printReportAfterTransaction
       {
         int $result = (int)0;
         $result = this.printReportAfterTransaction ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 6:  // DETApp/DET/trapBalance
       {
         this.trapBalance ();
         out = $rh.createReply();
         break;
       }

       case 7:  // DETApp/DET/trapQuantity
       {
         this.trapQuantity ();
         out = $rh.createReply();
         break;
       }

       case 8:  // DETApp/DET/setRequestForBalance
       {
         String versionName = in.read_string ();
         String commName = in.read_string ();
         int reqID = in.read_long ();
         String argument = in.read_string ();
         this.setRequestForBalance (versionName, commName, reqID, argument);
         out = $rh.createReply();
         break;
       }

       case 9:  // DETApp/DET/setRequestForQuantity
       {
         String versionName = in.read_string ();
         String commName = in.read_string ();
         int reqID = in.read_long ();
         int argument = in.read_long ();
         this.setRequestForQuantity (versionName, commName, reqID, argument);
         out = $rh.createReply();
         break;
       }


  //long sellItem(int String item, in long qty,in double bal);
       case 10:  // DETApp/DET/sellItem
       {
         int qty = in.read_long ();
         double bal = in.read_double ();
         int $result = (int)0;
         $result = this.sellItem (qty, bal);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 11:  // DETApp/DET/tradeItems
       {
         String item1 = in.read_string ();
         int qty1 = in.read_long ();
         String item2 = in.read_string ();
         int qty2 = in.read_long ();
         String etrader = in.read_string ();
         int $result = (int)0;
         $result = this.tradeItems (item1, qty1, item2, qty2, etrader);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 12:  // DETApp/DET/addGenericTrapType
       {
         int genType = in.read_long ();
         this.addGenericTrapType (genType);
         out = $rh.createReply();
         break;
       }

       case 13:  // DETApp/DET/signalTrapTypeGeneric
       {
         String trapType = in.read_string ();
         this.signalTrapTypeGeneric (trapType);
         out = $rh.createReply();
         break;
       }

       case 14:  // DETApp/DET/getTrapNameGeneric
       {
         String $result = null;
         $result = this.getTrapNameGeneric ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 15:  // DETApp/DET/addSpecificTrapType
       {
         int speType = in.read_long ();
         this.addSpecificTrapType (speType);
         out = $rh.createReply();
         break;
       }

       case 16:  // DETApp/DET/signalTrapTypeSpecific
       {
         String trapType = in.read_string ();
         this.signalTrapTypeSpecific (trapType);
         out = $rh.createReply();
         break;
       }

       case 17:  // DETApp/DET/getTrapNameSpecific
       {
         String $result = null;
         $result = this.getTrapNameSpecific ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DETApp/DET:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DET _this() 
  {
    return DETHelper.narrow(
    super._this_object());
  }

  public DET _this(org.omg.CORBA.ORB orb) 
  {
    return DETHelper.narrow(
    super._this_object(orb));
  }


} // class DETPOA
